allow to add timestamp suffix to log path
BourgondAries/file-rotate pull request #1
Opened 2020-03-08 04:33 UTC by gfreezy

2020-11-24 18:08 UTC, BourgondAries commented
Not sure why this is needed. File metadata already contains the timestamp.

2020-11-25 01:07 UTC, gfreezy commented
After restarting the process, the new log starts with `xxxx.log` which will overwrite the previous run's log. If we want to keep the previous run's log, we have to rename `xxxx.log` to `xxx.log.1`, then `xxx.log.1` will be overwritten. So we have to rename all the `xxx.log.xx` which is very verbose.

With timestamp suffix, renaming the previous run's `xxx.log` to `xxx.log.timestamp-suffix` is enough.

2020-11-26 00:50 UTC, BourgondAries commented
That's a good case, thanks for explaining. Can you please resolve the conflicts currently?

2021-08-19 09:39 UTC, Ploppz commented
@gfreezy  I think I'll build on this branch in an upcoming PR. Will you fix the conflicts? Otherwise I'll just include your changes in my PR.

2021-08-19 11:20 UTC, gfreezy commented
@BourgondAries Conflicts resolved.

2021-08-19 12:55 UTC, Ploppz commented
One thought:

How does this work if you use it in an application that might stop and then start again?
It will forget `log_paths` and thus fail to remove old files. Maybe we need to do a directory listing in `new()` and parse file names to construct `log_paths`? What do you think?

2021-08-21 13:46 UTC, BourgondAries requested changes
If you'd like this added please put it behind a feature to keep the core as simple as possible. I'd like to keep it backwards compatible too.
Please squash the commits.

2021-08-21 13:46 UTC, BourgondAries commented on README.md
> +
Trailing newline

2021-08-21 13:46 UTC, BourgondAries commented on README.md
> +
What's going on here? Replacing \n by \n\r? We should not have this in the diff.

2021-08-21 13:46 UTC, BourgondAries commented on Cargo.toml
> +chrono = "0.4.11"
Put this behind a feature.

2021-08-23 13:32 UTC, Ploppz commented
Will be difficult in this PR to put chrono behind a feature, because there is no option anymore to use a simple count as suffix. I'm fixing that in my branch.

2021-08-23 15:19 UTC, gfreezy commented
It's difficult to be backwards compatible. I will close the PR.  It is a lot of work to implement features like https://docs.rs/log4rs/1.0.0/log4rs/append/rolling_file/struct.RollingFileAppenderDeserializer.html#configuration or https://docs.rs/tracing-appender/0.1.2/tracing_appender/ .

2021-08-23 15:19 UTC, closed without merging